# Blog
title: Hannes Moser
email: box@hannes-moser.com
description: >
  Seasoned software developer with a passion for web technology. Working on
  distributed systems, data pipelines, discovery systems, real-time systems,
  and AI-driven products. Lectures computer science at the University of Applied
  Sciences Salzburg.

baseurl: ""
url: "https://www.hannesmoser.at"
logo: /assets/images/author-2024.jpg
cover: /assets/images/header.jpg

# Author
twitter_username: eliias
github_username:  eliias

author: Hannes Moser
author_image: /assets/images/author-2024.jpg

collections:
  journey:
    sort_by: date

# Build settings
markdown: kramdown

plugins:
  - jekyll/vite
  - jekyll-feed

exclude:
  - bin
  - config
  - vite.config.ts
  - tmp
  - Procfile.dev
  - .sass-cache/
  - .jekyll-cache/
  - docs/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

