# Site settings
title: Hannes Moser
email: box@hannesmoser.at
description: >
  The core topic of Hannes work is the WWW. He is proficient in designing web services and he also can be the architect of your next big web application.
  His weapons of choice are modern programing languages and paradigms. He has a special interest in reactive applications, API design and media streaming/transcoding.
  He also used to work as an operations engineer for several big websites. Creating a stable infrustructure and identifying performance bottlenecks is his pleasure.
  Hannes is available for project, freelance and consulting work. If you want him to sit next to you, be aware of his licking dog.
baseurl: "/"
url: "https://hannesmoser.at"
twitter_username: eliias
github_username:  eliias

sass:
  sass_dir: css
  style: compressed

# Build settings
markdown: kramdown

exclude: ["node_modules", "package.json", "package-lock.json"]
